### ISSUE TITLE
Build Failure?

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-roq#274]
I just checked out the latest code on Windows and I get this failure? 

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.126 s <<< FAILURE! -- in io.quarkiverse.roq.data.test.RoqDataInjectableBeanLookingDefaultLocationTest
[ERROR] io.quarkiverse.roq.data.test.RoqDataInjectableBeanLookingDefaultLocationTest -- Time elapsed: 1.126 s <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to load steps from class io.quarkiverse.roq.data.deployment.RoqDataReaderProcessor
        at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:736)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: Failed to load steps from class io.quarkiverse.roq.data.deployment.RoqDataReaderProcessor
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:169)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:350)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:272)
        at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:682)
        ... 1 more
Caused by: java.lang.NoClassDefFoundError: DataConverterFinder
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578)
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2676)
        at io.quarkus.deployment.ExtensionLoader.getMethods(ExtensionLoader.java:934)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFromClass(ExtensionLoader.java:437)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:167)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: DataConverterFinder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 11 more
```

**Comment by melloware** [comment]
Actually did a full clean and now i get this on the Blog.

```
[INFO] Running io.quarkiverse.roq.it.RoqBlogTest
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 5, Time elapsed: 3.719 s <<< FAILURE! -- in io.quarkiverse.roq.it.RoqBlogTest
[ERROR] io.quarkiverse.roq.it.RoqBlogTest.testTag -- Time elapsed: 0.007 s <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to load steps from class io.quarkiverse.roq.plugin.aliases.deployment.RoqPluginAliasesProcessor
        at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:632)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:716)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: Failed to load steps from class io.quarkiverse.roq.plugin.aliases.deployment.RoqPluginAliasesProcessor
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:169)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:350)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:272)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:62)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:216)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:599)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:649)
        ... 1 more
Caused by: java.lang.NoClassDefFoundError: RoqFrontMatterAliasesRecorder
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578)
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2676)
        at io.quarkus.deployment.ExtensionLoader.getMethods(ExtensionLoader.java:934)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFromClass(ExtensionLoader.java:437)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:167)
        ... 8 more
Caused by: java.lang.ClassNotFoundException: RoqFrontMatterAliasesRecorder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:569)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:517)
        ... 14 more
```

**Comment by ia3andy** [comment]
@melloware are you still experiencing this?

**Comment by melloware** [comment]
I just did a full pull and now when I run `mvn clean install` on Windows I get this error

```
[ERROR] Failures:
[ERROR]   RoqDataDevModeTest.changeData:31 1 expectation failed.
Expected status code <200> but was <404>.
```

**Comment by ia3andy** [comment]
ok I guess the test is relying on a path 😅, let me fix this

**Comment by melloware** [comment]
Apologies!   I had something running on port 8080 i just tried again and all is passing!
